### ISSUE TITLE
biographyページの写真がずれている。

### ISSUE THREAD

**Issue by kyotaodagiri** [MSY-a/KYRIE-HP#2]
写真がPCサイズで中央より左にずれている。
意図した状態なのか意図しない状態かを確認して、
必要であればブランチ切って、修正して下さい。

**Comment by MSY-a** [comment]
意図しない状態だったので修正しました。

[https://github.com/MSY-a/KYRIE-HP/tree/develop/photo](https://github.com/MSY-a/KYRIE-HP/tree/develop/photo)

**Comment by kyotaodagiri** [comment]
[PR4](https://github.com/MSY-a/KYRIE-HP/pull/4)で解消済みの為、クローズ
