### ISSUE TITLE
スペルミス

### ISSUE THREAD

**Issue by kyotaodagiri** [MSY-a/KYRIE-HP#8]
https://github.com/MSY-a/KYRIE-HP/blob/903df6473fe09930a91445bce99cb7c0d8248716/top.html#L66

このファイルだけじゃないけど、「coming soon」でm多いと思う。

**Comment by MSY-a** [comment]
coming soon...のスペル修正を各ページ行いました。
また、メディアクエリの記述を見えやすいように字下げしました。

[develop/spell_correction](https://github.com/MSY-a/KYRIE-HP/tree/develop/spell_correction)
